### ISSUE TITLE
Token Shrinks When Mounting Certain Other Tokens

### ISSUE THREAD

**Issue by Simon-Magnus** [Saibot393/Rideable#121]
Sometimes when trying to mount a token, the mountee will visually shrink until it is invisible. Unmounting causes the token to grow back to its original size. 

I'm not sure what causes this issue, but I do know that toggling 'Scale (Ratio)' to locked on the mount token 'fixes' the issue. In reality, it seems like doing this breaks something else. I've added an image of the error from the console under this condition. This persists after unlocking the Scale.

<img width="1192" height="316" alt="Image" src="https://github.com/user-attachments/assets/0fcb1ce5-a4c8-4586-8440-cf4964ee7cf6" />

Not every token that has had its scale modified seems to suffer from this, but all the tokens that did had the Dynamic Token Ring on. Turning the Dynamic Token Ring off after the fact does *not* fix the problem, though.

**Comment by Saibot393** [comment]
I have two ideas what might cause this behaviour, to test what it could be, could you do the following two things:

1. Select one of the Mount tokens for which this bug happens, open the console, enter this into the console `canvas.tokens.controlled[0].document.flags.Rideable.RidersScaleFlag` and send me the output?
2. Enter this into the console `game.settings.get("Rideable", "RiderScaleFactor")` and send me the output 

In anyway, the bug should probably be fixed with v4.0.20

Also for the second error, could you also send me the console output of this `game.settings.get("Rideable", "MountingEffectsFlag")`?

**Comment by KJTailor** [comment]
I'm on `4.0.20` and the bug still happens to me.
What helps it is if I set the Rider Scale on the 'to be ridden' token to `1`, then the token does not shrink down to near nothing.

**Comment by Saibot393** [comment]
What was it set to befreien you set it to 1?
I will release an update that will Filters out this behaviour in a few hours

**Comment by KJTailor** [comment]
Before I set it to `1` it was empty, nothing

**Comment by Saibot393** [comment]
Hmm, that should not Happen, i will look into it
