### ISSUE TITLE
Mount on Enter does not seem to work.

### ISSUE THREAD

**Issue by devteamplus** [Saibot393/Rideable#30]
I turned on the "Mount on Enter" availability in the global settings.  I then set a token to allow "Mount on Enter".  However, moving tokens within the space of that rideable token do not mount the token.

Foundry v11.308
Rideable v2.7.1
OS: Linux AWS using NodeJS v16

**Comment by devteamplus** [comment]
Here's a video link to see what I'm seeing:

https://app.screencast.com/Do8lMZ08raSkl

**Comment by Saibot393** [comment]
I think i found the bug, should be fixed with v2.7.2. 
Also, that is probably the most beautiful scene (Battlemap and Tokens) i have ever seen in any VTT.

**Comment by devteamplus** [comment]
Thanks.. it’s a base Baileywiki Town Center map, with my own customizations.  😊


***@***.***
Lee Fuller
Chief Technology Officer




Phone/Text: 951-216-3560
Email:  ***@***.******@***.***>

**Comment by devteamplus** [comment]
Just a side note here...
I have successfully mounted a token using "on enter".  And if there are other tokens on it, like the party wagon you see in the video... the other mounted tokens rearrange positions as they should.  However, when one of those tokens dismounts, the arrangement is still the same, until the ridden token moves.  Would it be logical to rearrange the tokens still mounted back to proper positioning, once one of the tokens dismounts? 

I can see that it may be problematic if they arrange themselves so that one of the still-mounted tokens arranges itself on top of the dismounted token.  So, this is why I'm asking.

Thanks for the super quick responses!

**Comment by Saibot393** [comment]
The problem would be exactly as you described, the tokens left mounted would rearrange and the unmounted token would probably be hard or impossible to select. I could implement something that checks if a token has left the mounted token and only then rearranges the tokens but that would be quite resource intensive for very little gain. I will therefore probably leave it as is for now, considering that it is (in my opinion) a small annoyance at worst.
